site_name: Performance Portability
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
theme: 'material'
extra:
  palette:
    primary: 'green'
    accent: 'yellow'
  logo: 'images/oos.png'
pages:
- Introduction: index.md
- Office of Science Facilities:
    - Overview: facilities/overview.md
    - Tools: facilities/tools.md
    - Comparison: facilities/comparison.md
- Performance Portability:
    - Definition: perfport/definition.md
    - Measurements: 
        - Measurement Techniques: perfport/measurements/index.md
        - Measuring Roofline Data on KNL: perfport/measurements/knl.md
        - Measuring Roofline Data on GPUs: perfport/measurements/gpu.md
    - Approaches:
        - Libraries: perfport/libraries/index.md
        - Directives:
            - OpenACC: perfport/directives/openacc.md
            - OpenMP: perfport/directives/openmp.md
        - Frameworks:
            - Kokkos: perfport/frameworks/kokkos.md
            - RAJA: perfport/frameworks/raja.md
        - DSL: perfport/dsl/index.md
        - Summary: perfport/summary/index.md
    - Case Studies:
        - BoxLib:
          - Overview: case_studies/amr/overview.md
          - Parallelism: case_studies/amr/parallelism.md
          - Code Layout: case_studies/amr/code_layout.md
          - Geometric Multigrid: case_studies/amr/multigrid.md
          - Porting:
            - Kokkos: case_studies/amr/port_to_kokkos.md
            - OpenMP 4.x: case_studies/amr/port_to_openmp.md
        - GW Kernels: case_studies/gw/index.md
        - QCD:
          - Overview: case_studies/qcd/overview.md
          - Code Structure: case_studies/qcd/code_structure.md
          - Kokkos Implementation: case_studies/qcd/kokkos_implementation.md
        - NekBone: case_studies/nek/index.md
        - MD: case_studies/md/index.md
- Other Resources: resources.md
- Demo: demo/demo.md
