site_name: Performance Portability
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - admonition
  - fontawesome_markdown
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
theme: 'material'
theme_dir: 'theme'
#theme_dir: 'theme/material/'
#site_favicon: favicon.ico
extra:
  palette:
    primary: 'green'
    accent: 'yellow'
##    logo: 'images/oos.png'
pages:
- Introduction: index.md
- Office of Science Facilities:
    - Overview: facilities/overview.md
    - Tools: facilities/tools.md
    - Comparison: facilities/comparison.md
- Performance Portability:
    - Overview: perfport/overview/index.md
    - Definition: perfport/definition.md
    - Measurements: 
        - Measurement Techniques: perfport/measurements/index.md
        - Collecting Roofline on KNL: perfport/measurements/knl.md
        - Collecting Roofline on GPUs: perfport/measurements/gpu.md
    - Strategy: perfport/strategy.md
    - Approaches:
        - Libraries: perfport/libraries/index.md
        - Directives:
            - OpenACC: perfport/directives/openacc.md
            - OpenMP: perfport/directives/openmp.md
        - Frameworks:
            - Kokkos: perfport/frameworks/kokkos.md
            - RAJA: perfport/frameworks/raja.md
        - DSL: perfport/dsl/index.md
    - Case Studies:
        - BoxLib:
          - Overview: case_studies/amr/overview.md
          - Parallelism: case_studies/amr/parallelism.md
          - Code Structure: case_studies/amr/code_structure.md
          - Geometric Multigrid: case_studies/amr/multigrid.md
          - Implementations:
            - Kokkos: case_studies/amr/kokkos_implementation.md
            - RAJA: case_studies/amr/raja_implementation.md
            - OpenMP 4.x: case_studies/amr/openmp_implementation.md
          - Performance: case_studies/amr/performance_comparison.md
        - BGW: 
          - Overview: case_studies/gw/index.md
          - Code structure: case_studies/gw/code_structure.md
          - Implementations:
            - Kokkos: case_studies/gw/kokkos_implementation.md
            - OpenMP 4.x: case_studies/gw/openmp_implementation.md
#          - Summary: case_studies/gw/summary.md
        - QCD:
          - Overview: case_studies/qcd/overview.md
          - Code Structure: case_studies/qcd/code_structure.md
          - Implementations:
            - Kokkos: case_studies/qcd/kokkos_implementation.md
          - Results: case_studies/qcd/results_summary.md
        - NekBone: case_studies/nek/index.md
        - MD: case_studies/md/index.md
    - Summary: perfport/summary/index.md
- Other Resources: resources.md
# see Brandon's markdown demo page here:
#- Demo: demo/demo.md
